### ISSUE TITLE
Generator points to wrong dictionary for json files

### ISSUE THREAD

**Issue by antoniusostermann** [webcomputing/AssistantJS#27]
Generating a new application and running `assistant g` with json files configured doesn't work anymore.

```
{ Error: Cannot find module '/[...]/js/config/locales/de/entities.json'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Generator.loadJsOrJson (assistant-source/lib/components/unifier/generator.js:246:20)
```

**Comment by baflo** [comment]
PR #38 sollte dies beheben, basiert jedoch auf einem Branch, der noch keine Custom Entities kennt. Siehe auch https://trello.com/c/s1PflEWP

**Comment by antoniusostermann** [comment]
Seems to work with new locales loader
