### ISSUE TITLE
Cannot recreate spec setup

### ISSUE THREAD

**Issue by baflo** [webcomputing/AssistantJS#39]
Tried to run two intents which failed (error below);

```js
describe("MainState", function() {
  beforeEach(async function(this: CurrentThisContext) {
    this.specHelper.prepareSpec(this.defaultSpecOptions);
  });

  describe("#cancelGenericIntent", function() {
    beforeEach(async function(this: CurrentThisContext) {
      await this.specHelper.prepareIntentCall(this.platforms.alexa, "cancelGenericIntent"); // TODO: this.platforms.alexa doesn't exist yet, see setup.js!
      this.responseResults = await this.specHelper.runMachineAndGetResults("MainState");
    });

    it("returns 'Bye'", async function(this: CurrentThisContext) {
      expect(this.responseResults.voiceMessage!.text).toEqual("Bye");
    });
  });

  describe("#invokeGenericIntent", function() {
    beforeEach(async function(this: CurrentThisContext) {
      await this.specHelper.prepareIntentCall(this.platforms.alexa, "invokeGenericIntent"); // TODO: this.platforms.alexa doesn't exist yet, see setup.js!
      this.responseResults = await this.specHelper.runMachineAndGetResults("MainState");
    });

    it("returns 'helloWorld'", async function(this: CurrentThisContext) {
      expect(this.responseResults.voiceMessage!.text).toEqual("Hello World");
    });
  });
});
```

*Error messages*
```
> jasmine-ts spec/**/*.spec.ts

Started
.(node:22280) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
F

Failures:
1) MainState #invokeGenericIntent returns 'helloWorld'
  Message:
    Error: Component alexa is already registered!
  Stack:
    Error: Component alexa is already registered!
        at ComponentRegistry.add (C:\Users\fb\Projects\AssistantJS\node_modules\inversify-components\lib\component\registry.js:25:19)
        at ComponentRegistry.addFromDescriptor (C:\Users\fb\Projects\AssistantJS\node_modules\inversify-components\lib\component\registry.js:33:14)
        at components.forEach.component (C:\Users\fb\Projects\AssistantJS\lib\setup.js:26:74)
        at Array.forEach (<anonymous>)
        at AssistantJSSetup.registerComponents (C:\Users\fb\Projects\AssistantJS\lib\setup.js:26:20)
        at AssistantJSSetup.registerComponent (C:\Users\fb\Projects\AssistantJS\lib\setup.js:22:14)
        at ApplicationInitializer.initializeSetups (C:\Users\fb\Projects\ts-translation-completion-test\application-initializer.ts:31:22)
        at ApplicationInitializer.createAndPrepareSetups (C:\Users\fb\Projects\ts-translation-completion-test\application-initializer.ts:95:10)
        at UserContext.<anonymous> (C:\Users\fb\Projects\ts-translation-completion-test\spec\helpers\setup.js:9:45)
  Message:
    TypeError: Cannot read property 'prepareSpec' of undefined
  Stack:
    TypeError: Cannot read property 'prepareSpec' of undefined
        at UserContext.<anonymous> (C:\Users\fb\Projects\ts-translation-completion-test\spec\app\states\main.spec.ts:10:21)
        at Generator.next (<anonymous>)
        at C:\Users\fb\Projects\ts-translation-completion-test\spec\app\states\main.spec.ts:7:71
        at new Promise (<anonymous>)
        at __awaiter (C:\Users\fb\Projects\ts-translation-completion-test\spec\app\states\main.spec.ts:3:12)
        at UserContext.<anonymous> (C:\Users\fb\Projects\ts-translation-completion-test\spec\app\states\main.spec.ts:13:16)
  Message:
    TypeError: Cannot read property 'prepareIntentCall' of undefined
  Stack:
    TypeError: Cannot read property 'prepareIntentCall' of undefined
        at UserContext.<anonymous> (C:\Users\fb\Projects\ts-translation-completion-test\spec\app\states\main.spec.ts:26:29)
        at Generator.next (<anonymous>)
        at C:\Users\fb\Projects\ts-translation-completion-test\spec\app\states\main.spec.ts:7:71
        at new Promise (<anonymous>)
        at __awaiter (C:\Users\fb\Projects\ts-translation-completion-test\spec\app\states\main.spec.ts:3:12)
        at UserContext.<anonymous> (C:\Users\fb\Projects\ts-translation-completion-test\spec\app\states\main.spec.ts:32:20)
  Message:
    TypeError: Cannot read property 'voiceMessage' of undefined
  Stack:
    TypeError: Cannot read property 'voiceMessage' of undefined
        at UserContext.<anonymous> (C:\Users\fb\Projects\ts-translation-completion-test\spec\app\states\main.spec.ts:31:35)
        at Generator.next (<anonymous>)
        at C:\Users\fb\Projects\ts-translation-completion-test\spec\app\states\main.spec.ts:7:71
        at new Promise (<anonymous>)
        at __awaiter (C:\Users\fb\Projects\ts-translation-completion-test\spec\app\states\main.spec.ts:3:12)
        at UserContext.<anonymous> (C:\Users\fb\Projects\ts-translation-completion-test\spec\app\states\main.spec.ts:38:20)

2 specs, 1 failure
Finished in 0.053 seconds

npm ERR! Test failed.  See above for more details.
```

**Comment by antoniusostermann** [comment]
Is fixed on current develop
